== Customization

By default, this extension provides a sensible auto-configuration for Logbook. However, you can easily customize nearly every aspect of its behavior by providing your own CDI beans.

The `LogbookProvider` will automatically inject any CDI beans that implement the following Logbook interfaces.

=== Providing a custom `Logbook` instance

If you need complete control over the Logbook configuration, you can provide your own `Logbook` bean. This will disable the default auto-configuration.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;
import org.zalando.logbook.Logbook;

@ApplicationScoped
public class CustomLogbookProvider {

    @Produces
    public Logbook customLogbook() {
        return Logbook.builder()
                // your custom configuration
                .build();
    }
}
----

=== Customizing Filters

You can add custom filters by creating CDI beans that implement the corresponding filter interfaces. You can have multiple beans for each filter type. For more details, see the official https://github.com/zalando/logbook#filtering[Logbook documentation].

==== `HeaderFilter`

Filters headers to prevent logging of sensitive information.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.HeaderFilter;

@ApplicationScoped
public class CustomHeaderFilter implements HeaderFilter {
    // implementation
}
----

==== `PathFilter`

Filters request paths.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.PathFilter;

@ApplicationScoped
public class CustomPathFilter implements PathFilter {
    // implementation
}
----

==== `QueryFilter`

Filters query parameters from the request URI.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.QueryFilter;

@ApplicationScoped
public class CustomQueryFilter implements QueryFilter {
    // implementation
}
----

==== `BodyFilter`

Filters the body of requests and responses.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.BodyFilter;

@ApplicationScoped
public class CustomBodyFilter implements BodyFilter {
    // implementation
}
----

==== `RequestFilter`

A low-level filter that operates on the entire `HttpRequest`.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.RequestFilter;

@ApplicationScoped
public class CustomRequestFilter implements RequestFilter {
    // implementation
}
----

==== `ResponseFilter`

A low-level filter that operates on the entire `HttpResponse`.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.ResponseFilter;

@ApplicationScoped
public class CustomResponseFilter implements ResponseFilter {
    // implementation
}
----

=== Other customizations

You can also customize other parts of Logbook by providing beans for the following interfaces.

==== `HttpLogFormatter`

Defines how requests and responses are transformed into strings. See the https://github.com/zalando/logbook#formatting[Logbook documentation] for available formatters.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.HttpLogFormatter;

@ApplicationScoped
public class CustomHttpLogFormatter implements HttpLogFormatter {
    // implementation
}
----

==== `HttpLogWriter`

Defines where the formatted requests and responses are written to. See the https://github.com/zalando/logbook#writing[Logbook documentation] for more details.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.HttpLogWriter;

@ApplicationScoped
public class CustomHttpLogWriter implements HttpLogWriter {
    // implementation
}
----

==== `Strategy`

Defines how and when requests and responses are logged. See the https://github.com/zalando/logbook#strategy[Logbook documentation] for built-in strategies.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.Strategy;

@ApplicationScoped
public class CustomStrategy implements Strategy {
    // implementation
}
----

==== `AttributeExtractor`

Extracts a list of key/value pairs from requests and/or responses to be included in the logs. See the https://github.com/zalando/logbook#attribute-extractor[Logbook documentation] for more details.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.attributes.AttributeExtractor;

@ApplicationScoped
public class CustomAttributeExtractor implements AttributeExtractor {
    // implementation
}
----

==== `CorrelationId`

Generates a correlation ID to link requests and responses. See the https://github.com/zalando/logbook#correlation[Logbook documentation] for more information.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.CorrelationId;

@ApplicationScoped
public class CustomCorrelationId implements CorrelationId {
    // implementation
}
----

==== `Sink`

A combination of `HttpLogFormatter` and `HttpLogWriter` that allows for more sophisticated writing strategies. See the https://github.com/zalando/logbook#sink[Logbook documentation] for more details.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.zalando.logbook.Sink;

@ApplicationScoped
public class CustomSink implements Sink {
    // implementation
}
----