== Customization

By default, this extension provides a sensible auto-configuration for Logbook. However, you can easily customize nearly every aspect of its behavior by providing your own CDI beans.

The `LogbookProvider` will automatically inject any CDI beans that implement the following Logbook interfaces.

=== Providing a custom `Logbook` instance

If you need complete control over the Logbook configuration, you can provide your own `Logbook` bean. This will disable the default auto-configuration.

[source,java]
----
include::../examples/CustomLogbookProvider.java[]
----

=== Customizing Filters

You can add custom filters by creating CDI beans that implement the corresponding filter interfaces. You can have multiple beans for each filter type. For more details, see the official https://github.com/zalando/logbook#filtering[Logbook documentation].

==== `HeaderFilter`

Filters headers to prevent logging of sensitive information.

[source,java]
----
include::../examples/CustomHeaderFilter.java[]
----

==== `PathFilter`

Filters request paths.

[source,java]
----
include::../examples/CustomPathFilter.java[]
----

==== `QueryFilter`

Filters query parameters from the request URI.

[source,java]
----
include::../examples/CustomQueryFilter.java[]
----

==== `BodyFilter`

Filters the body of requests and responses.

[source,java]
----
include::../examples/CustomBodyFilter.java[]
----

==== `RequestFilter`

A low-level filter that operates on the entire `HttpRequest`.

[source,java]
----
include::../examples/CustomRequestFilter.java[]
----

==== `ResponseFilter`

A low-level filter that operates on the entire `HttpResponse`.

[source,java]
----
include::../examples/CustomResponseFilter.java[]
----

=== Other customizations

You can also customize other parts of Logbook by providing beans for the following interfaces.

==== `HttpLogFormatter`

Defines how requests and responses are transformed into strings. See the https://github.com/zalando/logbook#formatting[Logbook documentation] for available formatters.

[source,java]
----
include::../examples/CustomHttpLogFormatter.java[]
----

==== `HttpLogWriter`

Defines where the formatted requests and responses are written to. See the https://github.com/zalando/logbook#writing[Logbook documentation] for more details.

[source,java]
----
include::../examples/CustomHttpLogWriter.java[]
----

==== `Strategy`

Defines how and when requests and responses are logged. See the https://github.com/zalando/logbook#strategy[Logbook documentation] for built-in strategies.

[source,java]
----
include::../examples/CustomStrategy.java[]
----

==== `AttributeExtractor`

Extracts a list of key/value pairs from requests and/or responses to be included in the logs. See the https://github.com/zalando/logbook#attribute-extractor[Logbook documentation] for more details.

[source,java]
----
include::../examples/CustomAttributeExtractor.java[]
----

==== `CorrelationId`

Generates a correlation ID to link requests and responses. See the https://github.com/zalando/logbook#correlation[Logbook documentation] for more information.

[source,java]
----
include::../examples/CustomCorrelationId.java[]
----

==== `Sink`

A combination of `HttpLogFormatter` and `HttpLogWriter` that allows for more sophisticated writing strategies. See the https://github.com/zalando/logbook#sink[Logbook documentation] for more details.

[source,java]
----
include::../examples/CustomSink.java[]
----